### ISSUE TITLE
Frontend lag with many entities

### ISSUE THREAD

**Issue by jojolepro** [randomPoison/amethyst-editor#26] opened 2018-10-04 21:08 UTC
34 entities, 150 components

Around 5 fps in the frontend. I'm not sure if its actually the frontend or the socket/processing having trouble.

**Comment by randomPoison** [comment] 2018-10-06 07:15
I think the easiest short-term fix is going to be randomPoison/amethyst-editor-sync#16. Longer term, the path towards consistent high-performance in the editor is #17. If lowering the sync rate is enough to keep the editor responsive under load, I'll close this issue out. Otherwise I can also look into being smarter about how we use Vue.js and how we manage the data in the editor.

**Comment by jojolepro** [comment] 2018-10-06 14:40
https://github.com/Akryum/vue-virtual-scroller

In the demo, check the "page mode" checkmark

**Comment by randomPoison** [comment] 2018-10-15 14:00
I believe this has been partially fixed by #16. @jojolepro could you try updating to version 0.2 of the editor and amethyst-editor-sync and let me know if the reduced update rate helps?

**Comment by randomPoison** [comment] 2018-10-20 03:13
@jojolepro confirmed in Discord that reducing the send rate fixed the latency problems. I'm going to close this for now since we already have issues open tracking the longer-term effort towards ensuring consistent high performance in the editor.

**Closed by randomPoison** 2018-10-20 03:13 UTC
Labels: bug, needs details
