### ISSUE TITLE
Crash: Message Too Long

### ISSUE THREAD

**Issue by jojolepro** [randomPoison/amethyst-editor#25] opened 2018-10-04 21:07 UTC
Already an issue on amethyst-editor-sync, but recreating here

issue thread '<unnamed>' panicked at 'Failed to send message: Os { code: 90, kind: Other, message: "Message too long" }', libcore/result.rs:1009:5

**Comment by randomPoison** [comment] 2018-10-04 21:20
Ah, no need to open an issue here since it's a duplicate of randomPoison/amethyst-editor-sync#12. Sorry, should have been more clear about that!

**Closed by randomPoison** 2018-10-04 21:20 UTC
